<?php
/*
 * This document has been generated with
 * https://mlocati.github.io/php-cs-fixer-configurator/#version:3.8.0|configurator
 * you can change this configuration by importing this file.
 */
$config = new PhpCsFixer\Config();

return $config
    ->setRiskyAllowed(true)
    ->setRules([
        'align_multiline_comment'                       => true,
        'array_indentation'                             => true,
        'array_syntax'                                  => ['syntax'=>'short'],
        'backtick_to_shell_exec'                        => true,
        'binary_operator_spaces'                        => ['default'=>'single_space','operators'=>['=>'=>'align_single_space_minimal','='=>'align_single_space_minimal']],
        'blank_line_after_namespace'                    => true,
        'blank_line_after_opening_tag'                  => true,
        'blank_line_before_statement'                   => true,
        'braces'                                        => true,
        'cast_spaces'                                   => true,
        'class_attributes_separation'                   => true,
        'class_definition'                              => true,
        'compact_nullable_typehint'                     => true,
        'concat_space'                                  => ['spacing'=>'one'],
        'constant_case'                                 => true,
        'control_structure_continuation_position'       => ['position'=>'same_line'],
        'echo_tag_syntax'                               => ['format'=>'long','shorten_simple_statements_only'=>true],
        'elseif'                                        => true,
        'encoding'                                      => true,
        'explicit_indirect_variable'                    => true,
        'explicit_string_variable'                      => true,
        'fully_qualified_strict_types'                  => true,
        'function_declaration'                          => true,
        'function_typehint_space'                       => true,
        'general_phpdoc_tag_rename'                     => true,
        'global_namespace_import'                       => ['import_constants'=>true,'import_functions'=>true],
        'indentation_type'                              => true,
        'lambda_not_used_import'                        => true,
        'line_ending'                                   => true,
        'linebreak_after_opening_tag'                   => true,
        'lowercase_cast'                                => true,
        'lowercase_keywords'                            => true,
        'lowercase_static_reference'                    => true,
        'magic_constant_casing'                         => true,
        'magic_method_casing'                           => true,
        'method_argument_space'                         => true,
        'method_chaining_indentation'                   => true,
        'multiline_comment_opening_closing'             => true,
        'multiline_whitespace_before_semicolons'        => ['strategy'=>'no_multi_line'],
        'native_function_casing'                        => true,
        'native_function_type_declaration_casing'       => true,
        'new_with_braces'                               => true,
        'no_alternative_syntax'                         => true,
        'no_blank_lines_after_class_opening'            => true,
        'no_blank_lines_after_phpdoc'                   => true,
        'no_break_comment'                              => true,
        'no_empty_comment'                              => true,
        'no_empty_phpdoc'                               => true,
        'no_empty_statement'                            => true,
        'no_extra_blank_lines'                          => true,
        'no_leading_import_slash'                       => true,
        'no_leading_namespace_whitespace'               => true,
        'no_multiline_whitespace_around_double_arrow'   => true,
        'no_php4_constructor'                           => true,
        'no_short_bool_cast'                            => true,
        'no_singleline_whitespace_before_semicolons'    => true,
        'no_spaces_after_function_name'                 => true,
        'no_spaces_around_offset'                       => true,
        'no_spaces_inside_parenthesis'                  => true,
        'no_superfluous_elseif'                         => true,
        'no_trailing_comma_in_singleline_array'         => true,
        'no_trailing_whitespace'                        => true,
        'no_trailing_whitespace_in_comment'             => true,
        'no_unneeded_control_parentheses'               => true,
        'no_unneeded_curly_braces'                      => true,
        'no_unused_imports'                             => true,
        'no_useless_else'                               => true,
        'no_useless_return'                             => true,
        'no_whitespace_before_comma_in_array'           => true,
        'no_whitespace_in_blank_line'                   => true,
        'normalize_index_brace'                         => true,
        'object_operator_without_whitespace'            => true,
        'operator_linebreak'                            => ['position'=>'beginning'],
        'ordered_class_elements'                        => true,
        'ordered_imports'                               => true,
        'phpdoc_add_missing_param_annotation'           => true,
        'phpdoc_align'                                  => true,
        'phpdoc_indent'                                 => true,
        'phpdoc_inline_tag_normalizer'                  => true,
        'phpdoc_line_span'                              => true,
        'phpdoc_no_package'                             => true,
        'phpdoc_no_useless_inheritdoc'                  => true,
        'phpdoc_order'                                  => true,
        'phpdoc_separation'                             => true,
        'phpdoc_trim'                                   => true,
        'phpdoc_trim_consecutive_blank_line_separation' => true,
        'phpdoc_types'                                  => true,
        'pow_to_exponentiation'                         => true,
        'psr_autoloading'                               => true,
        'return_assignment'                             => true,
        'return_type_declaration'                       => true,
        'semicolon_after_instruction'                   => true,
        'short_scalar_cast'                             => true,
        'simple_to_complex_string_variable'             => true,
        'simplified_if_return'                          => true,
        'single_blank_line_at_eof'                      => true,
        'single_blank_line_before_namespace'            => true,
        'single_class_element_per_statement'            => true,
        'single_import_per_statement'                   => true,
        'single_line_after_imports'                     => true,
        'single_line_comment_style'                     => true,
        'single_quote'                                  => true,
        'single_space_after_construct'                  => true,
        'space_after_semicolon'                         => true,
        'standardize_increment'                         => true,
        'standardize_not_equals'                        => true,
        'switch_case_semicolon_to_colon'                => true,
        'switch_case_space'                             => true,
        'switch_continue_to_break'                      => true,
        'ternary_operator_spaces'                       => true,
        'ternary_to_null_coalescing'                    => true,
        'trailing_comma_in_multiline'                   => ['elements'=>['arrays']],
        'trim_array_spaces'                             => true,
        'unary_operator_spaces'                         => true,
        'visibility_required'                           => ['elements'=>['method','property']],
        'whitespace_after_comma_in_array'               => true,
    ])
    ->setFinder(
        PhpCsFixer\Finder::create()
            ->exclude('vendor')
            ->exclude('bootstrap/cache')
            ->notPath('_ide_helper.php')
            ->notPath('_ide_helper_models.php')
            ->in(__DIR__)
    );
